name: Continuous Integration
on: [push]

jobs:
    tests:
        name: Tests
        runs-on: ubuntu-latest
        strategy:
            matrix:
                version: ['7.1', '7.2', '7.3']
        steps:
            - uses: actions/checkout@master
            - uses: baptouuuu/setup-php@1.0.2
              with:
                  version: ${{ matrix.version }}
            - run: 'composer self-update'
            - run: 'composer install --no-interaction'
            - run: 'composer ci'
